permalink: /:categories/:title/
url: "http://qazsweet.github.io"
full_name: "Qazsweet's blog"
first_name: "Erin"
last_name: "Sweet"
blog_title: "qazSweet"
author_img_name_path: "/images/users/user.png"
disqus_shortname: "example"
copyright_year: "2019"
google_analytics_code: ""
aboutme: "Time after time, c'est la vie."
