permalink: /:categories/:title/
url: "http://example.com"
full_name: "Qazsweet blog"
first_name: "Erin"
last_name: "Sweet"
blog_title: "Title"
author_img_name_path: "/images/users/user.png"
disqus_shortname: "example"
copyright_year: "2019"
google_analytics_code: ""
aboutme: "Time after time, c'est la vie."
